import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: const LoginAppPage(),
    );
  }
}

class LoginAppPage extends StatelessWidget {
  const LoginAppPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(body: ListView(children: const [Screen()]));
  }
}

class Screen extends StatelessWidget {
  const Screen({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1120,
          height: 2424.85,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFFF0FFF4),
            shape: RoundedRectangleBorder(
              side: BorderSide(
                width: 21.75,
                strokeAlign: BorderSide.strokeAlignOutside,
              ),
              borderRadius: BorderRadius.circular(48.93),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 1120,
                  height: 108.74,
                  padding: const EdgeInsets.symmetric(horizontal: 43.50),
                  child: Stack(
                    children: [
                      SizedBox(
                        width: 347.96,
                        height: double.infinity,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 10.87,
                          children: [
                            Text(
                              '9:30',
                              style: TextStyle(
                                color: const Color(0xFF181D18),
                                fontSize: 38.06,
                                fontFamily: 'Roboto',
                                fontWeight: FontWeight.w700,
                                height: 1.43,
                                letterSpacing: 0.68,
                              ),
                            ),
                            SizedBox(
                              width: 65.24,
                              height: 65.24,
                              child: Stack(),
                            ),
                          ],
                        ),
                      ),
                      Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.end,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Container(
                                width: 43.50,
                                height: 43.50,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(),
                                child: Stack(),
                              ),
                              Container(
                                width: 43.50,
                                height: 43.50,
                                clipBehavior: Clip.antiAlias,
                                decoration: BoxDecoration(),
                                child: Stack(),
                              ),
                            ],
                          ),
                          SizedBox(
                            height: 141.36,
                            child: Row(
                              mainAxisSize: MainAxisSize.min,
                              mainAxisAlignment: MainAxisAlignment.start,
                              crossAxisAlignment: CrossAxisAlignment.center,
                              spacing: 5.44,
                              children: [
                                Container(
                                  width: 43.50,
                                  height: 43.50,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                      Positioned(
                        left: 527.38,
                        top: 21.75,
                        child: SizedBox(
                          width: 65.24,
                          height: 65.24,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 65.24,
                                  height: 65.24,
                                  decoration: ShapeDecoration(
                                    color: Colors.black,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(
                                        271.84,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 2359.61,
                child: SizedBox(
                  width: 1120,
                  height: 65.24,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 413.20,
                        top: 27.18,
                        child: Container(
                          width: 293.59,
                          height: 10.87,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF202124),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(32.62),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 499,
                child: SizedBox(
                  width: 1047,
                  height: 138,
                  child: Text(
                    'Login/Cadastro',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 64,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 89,
                top: 831,
                child: Container(
                  width: 953,
                  height: 152,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 485,
                top: 888,
                child: SizedBox(
                  width: 149,
                  height: 38,
                  child: Text(
                    'e-mail',
                    style: TextStyle(
                      color: const Color(0xFF878686),
                      fontSize: 48,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 89,
                top: 1072,
                child: Container(
                  width: 953,
                  height: 151,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 490,
                top: 1119,
                child: SizedBox(
                  width: 140,
                  height: 58,
                  child: Text(
                    'senha',
                    style: TextStyle(
                      color: const Color(0xFF878686),
                      fontSize: 48,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 89,
                top: 1609,
                child: Container(
                  width: 953,
                  height: 153,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFD9D9D9),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1),
                      borderRadius: BorderRadius.circular(20),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 4),
                        spreadRadius: 0,
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 474,
                top: 1648,
                child: SizedBox(
                  width: 172,
                  height: 76,
                  child: Text(
                    'Login',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 64,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 324,
                top: 1942,
                child: SizedBox(
                  width: 459,
                  height: 88,
                  child: Text(
                    'Fazer cadastro',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 64,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 390,
                top: 2166,
                child: SizedBox(
                  width: 338,
                  height: 58,
                  child: Text(
                    'Esqueci senha',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 48,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 413,
                top: 161,
                child: SizedBox(
                  width: 557,
                  height: 75,
                  child: Text(
                    'FinControl',
                    style: TextStyle(
                      color: const Color(0xCC42AC27),
                      fontSize: 96,
                      fontFamily: 'DM Sans',
                      fontWeight: FontWeight.w500,
                      height: 1.18,
                      letterSpacing: -1.92,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 72,
                top: 69,
                child: Container(
                  width: 260,
                  height: 260,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/260x260"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(100),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 968,
                top: 151,
                child: Container(
                  width: 80,
                  height: 80,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 251,
                top: 1343,
                child: Container(
                  width: 140,
                  height: 140,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/140x140"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 729,
                top: 1348,
                child: Container(
                  width: 140,
                  height: 140,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/140x140"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 490,
                top: 1343,
                child: Container(
                  width: 140,
                  height: 140,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/140x140"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
